import { useEffect, useState } from 'react'
import { useAuth } from '../state/auth'
import { useCongregations } from '../lib/useCongregations'

const API = (import.meta.env.VITE_API_URL || '').replace(/\/$/, '')
function headers(){const token=localStorage.getItem('harvest_token')||'';return {Authorization:token?`Bearer ${token}`:'','Content-Type':'application/json'}}
async function request(path:string,init:RequestInit={}){const r=await fetch(`${API}${path}`,{...init,headers:{...headers(),...(init.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`Request failed (${r.status})`);return d}

function AdminPanel({onClose}:{onClose:()=>void}){const { congregations: groups } = useCongregations();
 const {isAdmin,username}=useAuth(); const [tab,setTab]=useState<'users'|'moderation'|'giving'|'audit'>('users'); const [q,setQ]=useState(''); const [users,setUsers]=useState<any[]>([]); const [pending,setPending]=useState<any[]>([]); const [giving,setGiving]=useState<any|null>(null); const [audit,setAudit]=useState<any[]>([]); const [edit,setEdit]=useState<any|null>(null); const [busy,setBusy]=useState(false); const [loading,setLoading]=useState(false); const [message,setMessage]=useState(''); const [error,setError]=useState('')
 const run=async(fn:()=>Promise<void>)=>{setLoading(true);setError('');try{await fn()}catch(e:any){setError(e.message||'Something went wrong')}finally{setLoading(false)}}
 const loadUsers=async()=>{const d=await request(`/api/users?q=${encodeURIComponent(q||'al')}`);setUsers(d.users||[])}
 const loadPending=async()=>{const d=await request('/api/pending?status=pending');setPending(d.pending||[])}
 const loadGiving=async()=>{setGiving(await request('/api/giving/admin'))}
 const loadAudit=async()=>{const d=await request('/api/admin/audit?limit=100');setAudit(d.audit||[])}
 useEffect(()=>{if(!isAdmin)return;void run(async()=>{await Promise.all([loadUsers(),loadPending(),loadGiving(),loadAudit()])})},[isAdmin])
 const updateUser=async(u:any,patch:any)=>{setBusy(true);setMessage('');setError('');try{await request(`/api/admin/users/${encodeURIComponent(u.username)}`,{method:'PATCH',body:JSON.stringify(patch)});setMessage(`@${u.username} updated`);setEdit(null);await loadUsers();await loadAudit()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 const lifecycle=async(u:any,action:'deactivate'|'restore'|'delete')=>{const prompt=action==='delete'?`Permanently delete @${u.username}? This cannot be undone.`:action==='deactivate'?`Deactivate @${u.username}? They will be unable to sign in until restored.`:`Restore @${u.username} and allow them to sign in again?`;if(!window.confirm(prompt))return;setBusy(true);setMessage('');setError('');try{const method=action==='delete'?'DELETE':'POST';await request(`/api/admin/users/${encodeURIComponent(u.username)}${action==='delete'?'':`/${action}`}`,{method});setMessage(action==='delete'?`@${u.username} permanently deleted`:`@${u.username} ${action}d`);await loadUsers();await loadAudit()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 const moderate=async(id:string,action:'approve'|'reject')=>{setBusy(true);setError('');try{await request(`/api/pending/${id}/${action}`,{method:'POST',body:action==='reject'?JSON.stringify({reason:'Rejected by administrator'}):'{}'});setMessage(`Content ${action}d`);await loadPending()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 const cleanup=async()=>{setBusy(true);try{const d=await request('/api/pending/cleanup',{method:'POST'});setMessage(`Cleanup complete: ${d.rows||0} records`);await loadPending()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 if(!isAdmin)return null
 return <div className="fixed inset-0 bg-[#141210]/90 z-[60] flex items-end justify-center" onClick={onClose}><div className="w-full max-w-[390px] max-h-[92vh] overflow-auto bg-stone-950 text-white rounded-t-3xl p-4 border-t border-stone-800" onClick={e=>e.stopPropagation()}>
  <div className="flex items-center justify-between mb-3"><div><p className="font-bold text-lg">Admin controls</p><p className="text-[11px] text-stone-400">Signed in as {username} · server-authorized administrator</p></div><button onClick={onClose} className="px-3 py-2 rounded-xl bg-stone-800">Close</button></div>
  <div className="grid grid-cols-4 gap-1 mb-4">{([['users','Members'],['moderation','Moderation'],['giving','Giving'],['audit','Audit']] as const).map(([k,l])=><button key={k} onClick={()=>setTab(k)} className={`py-2 rounded-xl text-[11px] font-semibold ${tab===k?'bg-[#7C3AED]':'bg-stone-900 border border-stone-800'}`}>{l}</button>)}</div>
  {loading&&<div className="mb-3 rounded-xl bg-stone-900 border border-stone-800 px-3 py-2 text-xs text-stone-400">Loading administrator data…</div>}{message&&<div className="mb-3 rounded-xl bg-emerald-950 border border-emerald-900 px-3 py-2 text-xs text-emerald-200">{message}</div>}{error&&<div className="mb-3 rounded-xl bg-red-950 border border-red-900 px-3 py-2 text-xs text-red-200">{error}</div>}
  {tab==='users'&&<><div className="flex gap-2 mb-3"><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&void run(loadUsers)} placeholder="Search members…" className="flex-1 rounded-xl bg-stone-900 border border-stone-800 px-3 py-2.5 text-sm"/><button disabled={loading||busy} onClick={()=>void run(loadUsers)} className="px-4 rounded-xl bg-white text-black text-xs font-bold">Search</button></div><div className="space-y-2">{users.map(u=><div key={u.username} className={`rounded-2xl bg-stone-900 border ${u.active===false?'border-red-950 opacity-80':'border-stone-800'} p-3`}><div className="flex items-center gap-2"><div className="w-9 h-9 rounded-full bg-[#7C3AED] flex items-center justify-center font-bold">{(u.name||u.username)[0].toUpperCase()}</div><div className="flex-1"><p className="text-sm font-semibold">{u.name} <span className="text-stone-500">@{u.username}</span></p><p className="text-[10px] text-stone-500">{u.role} · {u.group_name||'No group'} · {u.active===false?'Deactivated':'Active'}</p></div><span className={`text-[10px] px-2 py-1 rounded-full ${u.verified?'bg-emerald-900 text-emerald-300':'bg-stone-800 text-stone-400'}`}>{u.verified?'Verified':'Unverified'}</span></div><div className="grid grid-cols-2 gap-2 mt-3"><button disabled={busy||u.username===username||u.active===false} onClick={()=>setEdit(u)} className="py-2 rounded-xl bg-stone-800 text-xs font-semibold">Edit profile</button><select value={u.role} disabled={busy||u.username===username||u.active===false} onChange={e=>void updateUser(u,{role:e.target.value})} className="bg-stone-950 border border-stone-800 rounded-xl px-2 py-2 text-xs"><option value="member">Member</option><option value="admin">Admin</option></select></div><div className="grid grid-cols-2 gap-2 mt-2"><button disabled={busy||u.active===false} onClick={()=>void updateUser(u,{verified:!u.verified})} className="py-2 rounded-xl bg-stone-800 text-xs">{u.verified?'Unverify':'Verify'}</button><select value={u.group_name||groups[0]} disabled={busy||u.active===false} onChange={e=>void updateUser(u,{group_name:e.target.value})} className="bg-stone-950 border border-stone-800 rounded-xl px-2 py-2 text-xs">{groups.map(g=><option key={g}>{g}</option>)}</select></div><div className="grid grid-cols-2 gap-2 mt-2">{u.active===false?<button disabled={busy} onClick={()=>void lifecycle(u,'restore')} className="py-2 rounded-xl bg-emerald-900 text-emerald-200 text-xs font-bold">Restore account</button>:<button disabled={busy||u.username===username} onClick={()=>void lifecycle(u,'deactivate')} className="py-2 rounded-xl bg-amber-950 text-amber-200 text-xs font-bold">Deactivate</button>}<button disabled={busy||u.username===username} onClick={()=>void lifecycle(u,'delete')} className="py-2 rounded-xl bg-red-950 text-red-200 text-xs font-bold">Delete permanently</button></div></div>)}{!users.length&&!loading&&<p className="text-center text-xs text-stone-500 py-6">No members found.</p>}</div></>}
  {edit&&<div className="fixed inset-0 bg-[#141210]/80 z-[70] flex items-center justify-center p-4" onClick={()=>!busy&&setEdit(null)}><div className="w-full max-w-[370px] rounded-3xl bg-stone-950 border border-stone-800 p-4" onClick={e=>e.stopPropagation()}><div className="flex justify-between items-center mb-3"><div><p className="font-bold">Edit @{edit.username}</p><p className="text-[10px] text-stone-500">Changes are saved on the server and audited.</p></div><button disabled={busy} onClick={()=>setEdit(null)} className="text-stone-400">✕</button></div><div className="space-y-2">{(['name','phone','location','constituency','faith'] as const).map(f=><input key={f} defaultValue={edit[f]||''} id={`admin-${f}`} placeholder={f.replace('_',' ')} className="w-full rounded-xl bg-stone-900 border border-stone-800 px-3 py-2.5 text-sm"/>)}<select id="admin-group" defaultValue={edit.group_name||groups[0]} className="w-full rounded-xl bg-stone-900 border border-stone-800 px-3 py-2.5 text-sm">{groups.map(g=><option key={g}>{g}</option>)}</select><button disabled={busy} onClick={()=>void updateUser(edit,{name:(document.getElementById('admin-name') as HTMLInputElement).value,phone:(document.getElementById('admin-phone') as HTMLInputElement).value,location:(document.getElementById('admin-location') as HTMLInputElement).value,constituency:(document.getElementById('admin-constituency') as HTMLInputElement).value,faith:(document.getElementById('admin-faith') as HTMLInputElement).value,group_name:(document.getElementById('admin-group') as HTMLSelectElement).value})} className="w-full py-3 rounded-xl bg-white text-black text-sm font-bold">{busy?'Saving…':'Save profile'}</button></div></div></div>}
  {tab==='moderation'&&<><div className="flex justify-between items-center mb-3"><p className="text-sm font-bold">Pending content ({pending.length})</p><button onClick={()=>void cleanup()} disabled={busy} className="text-[11px] px-3 py-2 rounded-xl bg-stone-800">Clean stale uploads</button></div><div className="space-y-2">{pending.map(x=><div key={x.id} className="rounded-2xl bg-stone-900 border border-stone-800 p-3"><div className="flex justify-between"><p className="text-sm font-semibold">{x.type} · @{x.username}</p><span className="text-[10px] text-amber-400">pending</span></div><p className="text-xs text-stone-400 mt-1 line-clamp-2">{x.caption||'No caption'}</p><div className="grid grid-cols-2 gap-2 mt-3"><button disabled={busy} onClick={()=>void moderate(x.id,'approve')} className="py-2 rounded-xl bg-emerald-700 text-xs font-bold">Approve</button><button disabled={busy} onClick={()=>void moderate(x.id,'reject')} className="py-2 rounded-xl bg-red-900 text-xs font-bold">Reject</button></div></div>)}{!pending.length&&<p className="text-center text-xs text-stone-500 py-6">Nothing waiting for review.</p>}</div></>}
  {tab==='giving'&&<>{giving?<><div className="grid grid-cols-2 gap-2 mb-4"><div className="rounded-2xl bg-stone-900 p-4"><p className="text-[10px] text-stone-500">Completed</p><p className="text-xl font-bold">KES {giving.totals?.completed_kes||'0'}</p></div><div className="rounded-2xl bg-stone-900 p-4"><p className="text-[10px] text-stone-500">Pending</p><p className="text-xl font-bold">{giving.totals?.pending_count||0}</p></div></div>{(giving.transactions||[]).slice(0,30).map((x:any)=><div key={x.id} className="rounded-xl bg-stone-900 p-3 flex justify-between mb-2"><div><p className="text-xs font-semibold">@{x.username||'unknown'} · {x.purpose}</p><p className="text-[10px] text-stone-500">{x.status} · {x.receipt_number||'no receipt'}</p></div><b className="text-sm">KES {x.amount_kes}</b></div>)}</>:<p className="text-center text-xs text-stone-500 py-6">Loading giving…</p>}</>}
  {tab==='audit'&&<div className="space-y-2">{audit.map(x=><div key={x.id} className="rounded-xl bg-stone-900 border border-stone-800 p-3"><p className="text-xs font-semibold">{x.action} · {x.target_type}</p><p className="text-[10px] text-stone-500">by @{x.actor_username||'deleted-admin'} · {new Date(x.created_at).toLocaleString()}</p><pre className="mt-1 text-[9px] text-stone-400 whitespace-pre-wrap break-words">{JSON.stringify(x.meta)}</pre></div>)}{!audit.length&&<p className="text-center text-xs text-stone-500 py-6">No audit entries.</p>}</div>}
 </div></div>
}

export default function AccountSwitcher({users,onSwitch,onClose}:{users:any[];onSwitch:(u:string)=>void;onClose:()=>void}){
 const {isAdmin}=useAuth(); const demoAccountsEnabled=import.meta.env.DEV||import.meta.env.VITE_ENABLE_DEMO_ACCOUNTS==='true'; if(isAdmin)return <AdminPanel onClose={onClose}/>; if(!demoAccountsEnabled)return null; const current=(()=>{try{return JSON.parse(localStorage.getItem('harvest_users')||'[]')[0]?.username||localStorage.getItem('harvest_username')||'allan'}catch{return'allan'}})(); return <div className="fixed inset-0 bg-[#141210]/80 z-50 flex items-end justify-center" onClick={onClose}><div className="w-full max-w-[390px] bg-stone-900 rounded-t-2xl p-4 border-t border-stone-800" onClick={e=>e.stopPropagation()}><p className="text-sm font-bold text-white mb-3">Switch demo account</p>{users.slice(0,4).map((u:any)=><button key={u.username} onClick={()=>{onSwitch(u.username);onClose()}} className={`w-full flex items-center gap-3 p-3 rounded-xl mb-2 ${current===u.username?'bg-[#7C3AED]':'bg-stone-800'}`}><div className="w-10 h-10 rounded-full bg-gradient-to-tr from-yellow-400 to-purple-600 p-[2px]"><div className="w-full h-full rounded-full bg-[#141210] flex items-center justify-center text-xs font-bold">{u.username[0].toUpperCase()}</div></div><div className="flex-1 text-left"><p className="text-sm font-semibold text-white">{u.username}</p><p className="text-xs text-stone-400">{u.name} · {u.verified?'Verified':'Normal'} · {u.group}</p></div></button>)}<button onClick={onClose} className="w-full mt-3 py-3 rounded-full bg-stone-800 text-white text-sm">Close</button></div></div>
}
